### ISSUE TITLE
Support clean values in ScienceAsync mode

### ISSUE THREAD

**Issue by brafkind** [scientistproject/Scientist.net#113]
When running parallel candidates with ScienceAsync, it would be great to be able to clean the values before publishing.

**Comment by M-Zuber** [comment]
Could you define "clean" in this context?

**Comment by brafkind** [comment]
Same as described in the README here https://github.com/scientistproject/Scientist.net#keeping-it-clean

**Comment by M-Zuber** [comment]
My apologies, I only recently got back into this project and did not have a chance to fully familiarize myself with the changes since I was last here.

It would seem that these options are already available.
[This is the "simple" overload](https://github.com/scientistproject/Scientist.net/blob/e8345037eb4e3197fef5ced79dd87465cc7093e4/src/Scientist/Scientist.cs#L139) and [the overload that takes in a `concurrentTasks` parameter](https://github.com/scientistproject/Scientist.net/blob/e8345037eb4e3197fef5ced79dd87465cc7093e4/src/Scientist/Scientist.cs#L151)

**Comment by brafkind** [comment]
Ok, now I see how I can specific the TClean type as well. Thanks!
